from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional, AsyncGenerator
from pydantic import BaseModel


class LLMResponse(BaseModel):
    response_text: str
    intent: str = "conversational_reply"
    tone: str = "friendly_encouraging"
    follow_up: Optional[str] = None
    correction_guidance: Optional[str] = None
    difficulty: str = "intermediate"


class LLMProvider(ABC):
    """Abstract Base Class for LLM Providers."""

    @abstractmethod
    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        language: str = "en",
        user_context: Optional[Dict[str, Any]] = None,
        conversation_context: Optional[Dict[str, Any]] = None,
    ) -> LLMResponse:
        """Generate a complete structured response from the LLM."""
        pass

    @abstractmethod
    async def stream_response_chunks(
        self,
        messages: List[Dict[str, str]],
        language: str = "en",
        user_context: Optional[Dict[str, Any]] = None,
        conversation_context: Optional[Dict[str, Any]] = None,
    ) -> AsyncGenerator[str, None]:
        """Stream response text tokens/chunks as they are generated by the LLM."""
        pass
